version: '3.8'
services:
    app:
        build: .
        ports:
            - '80:80'
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
            - ./database:/var/www/html/database
        user: www-data
